version: '2'

services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    image: 'lccezinha/registermeapp:v1'
    depends_on:
      - 'db'
    build: .
    ports:
      - '8080:3005'
    volumes:
      - '.:/usr/src/app'
volumes:
  postgres:
