default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: registerme_development

test:
  <<: *default
  database: registerme_test
